version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: container_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: container_mysql
      MYSQL_USER: container_mysql
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: meu_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
